site_name: Developing with RingCentral
site_url: https://github.com/ringcentral/ringcentral-api-docs
#site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/ringcentral-api-docs
edit_uri: 
docs_dir: docs
theme:
  name: null
  custom_dir: bootstrap4-theme
  suppress_nextprev: true
  highlightjs: true
  hljs_languages:
    - http
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
#theme: bootstrap
extra_css: [extra.css]
extra_javascript: [fonts.js]
copyright: 2018, RingCentral, Inc.
google_analytics: ['UA-57519112-5', 'ringcentral-api-docs.readthedocs.io']
pages:
- 'Quick Start': 'quick-start/index.md'
- 'Development Basics': 
  - 'Authentication': 'basics/oauth.md'
  - 'URIs': 'basics/uris.md'
  - 'Rate Limits': 'basics/rate-limits.md'
  - 'Notifications': 'notifications/index.md'
  - 'Messaging': 'basics/messaging.md'
  - 'Publishing Your App': 'basics/publish.md'
  - 'Upgrading from Legacy API': 'basics/legacy_api_upgrade.md'
- 'Products':
  - 'Configuration': 'configuration/index.md'
  - 'Data': 'data/index.md'
#    - 'Overview': 'data/index.md'
#    - 'Data Archival': 'data/archival.md'
  - 'Fax': 'fax/index.md'
  - 'Glip Messaging': 'glip/index.md'
  - 'SMS/MMS': 'sms/index.md'
  - 'Voice': 'voice/index.md'

#- 'Call Logs':
#    - 'API Basics': 'calllog_api-basics.md'
#    - 'Using Detailed Call Log Data': 'calllog_detailed-call-logs.md'
#    - 'Call Recordings': 'calllog_call-recordings.md'
#    - 'Call Log Synchronization': 'calllog_sync.md'
#    - 'Development Concerns': 'calllog_development-concerns.md'
#- 'Messaging':
#    - 'Message Synchronization': 'messages_sync.md'
#- 'Glip Messaging':
#    - 'Overview': 'glip_api.md'
#    - 'Message Attachments': 'glip_message_attachments.md'
#    - 'Glip Bots': 'glip_bots.md'
