site_name: Developing with RingCentral
site_url: https://github.com/ringcentral/ringcentral-api-docs
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/ringcentral-api-docs.git
docs_dir: docs
theme: readthedocs
extra_css: [extra.css]
extra_javascript: [fonts.js]
pages:
- 'Preface': 'index.md'
- 'OAuth 2.0 Authentication & Authorization': 'oauth.md'
- 'Authorization Profile and Permission Invalidation': 'authorization_profile.md'
- 'Rate Limits': 'rate_limits.md'
- 'Exploring Account & Extension Settings': 'account_extension.md'
- 'Call Log':
    - 'Introduction': 'calllog_introduction.md'
    - 'API Basics': 'calllog_api-basics.md'
    - 'Using Detailed Call Log Data': 'calllog_detailed-call-logs.md'
    - 'Call Recordings': 'calllog_call-recordings.md'
    - 'Call Log Synchronization': 'calllog_sync.md'
    - 'Development Concerns': 'calllog_development-concerns.md'
- 'Data Archival': 'data-archival.md'
- 'Messages':
    - 'Introduction': 'messages_introduction.md'
    - 'SMS and Pager': 'messages_sms-and-pager.md'
    - 'Faxes': 'messages_faxes.md'
    - 'Message Sync': 'messages_sync.md'
- 'Making Calls': 
    - 'RingOut': 'ring_out.md'
    - 'URI Scheme' : 'uri_scheme.md'
    - 'WebRTC' : 'webRTC.md'
- 'Call Handling Setup':
    - 'Call Queues' : 'call_queue.md'   
    - 'Answering Rules' : 'answering_rules.md' 
- 'Push Notifications': 
    - 'Notifications and Subscriptions' : 'notifications_subscriptions.md'
    - 'Subscription Flow' : 'subscription_flow.md'
    - 'Notifications Transport' : 'notifications_transport.md' 
    - 'Webhooks': 'webhooks.md'
- 'Glip':
    - 'Introduction': 'glip_api.md'
    - 'Glip Bots': 'glip_bots.md'