site_name: Developing with RingCentral
site_url: https://github.com/ringcentral/ringcentral-api-docs
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/ringcentral-api-docs
edit_uri: tree/bootstrap-vertical-nav/docs
docs_dir: docs

plugins:
#  - git-committers:
#      repository: ringcentral/ringcentral-api-docs
#      branch: bootstrap-vertical-nav
#      token: cdd674ab06f6a621af3ea3f77a240b4ab9bbff2d
  - bootstrap-tables
#  - markdown-filter
#  - search-path:
#       path: 'code_samples/'

theme:
  name: bootstrap4
  custom_dir: 'theme/'
  suppress_nextprev: true
  shortcuts:
    - foo

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - codehilite:
      linenums: "None"

extra_css:
- https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css
- css/font-awesome.min.css
- css/code-styles.css
- css/code-tabs.css
- css/admonition.css
- https://fonts.googleapis.com/icon?family=Material+Icons
- https://cdn.rawgit.com/afeld/bootstrap-toc/v1.0.1/dist/bootstrap-toc.min.css
- css/base.css
- extra.css

header_javascript:
- https://code.jquery.com/jquery-3.3.1.slim.min.js
- fonts.js

footer_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js
- https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js
- https://cdn.rawgit.com/afeld/bootstrap-toc/v1.0.1/dist/bootstrap-toc.min.js
- js/base.js

copyright: "1999-2019 RingCentral, Inc. All rights reserved."

google_analytics: ['UA-57519112-5', 'ringcentral-api-docs.readthedocs.io']

pages:
- 'The Basics':
  - 'Get Started': 'get-started.md'
  - 'Using the API':
    - 'Methods, Endpoints and Parameters': 'basics/uris.md'
    - 'Developing in Sandbox': 'basics/sandbox.md'
    - 'Using Phones in Sandbox': 'basics/your-rc-phone.md'
    - 'Webhooks': 'basics/notifications/webhooks.md'
    - 'Mobile Push Notifications': 'basics/notifications/pubsub.md'
    - 'Rate Limits': 'basics/rate-limits.md'
  - 'Application Management':
    - 'Creating an Application': 'basics/create-app.md'
    - 'Deploying to Production': 'basics/production.md'
    - 'Publishing to App Gallery': 'basics/app-gallery.md'
    - 'Using Lead Forms': 'basics/lead-forms.md'
  - 'Account Management':
#    - 'Using the Developer Portal': 'basics/developer-portal.md'
    - 'Account & Extension Settings': 'basics/configuration/account_extension.md'    
    - 'Auth Profile & Permissions': 'basics/configuration/authorization_profile.md'
  - 'Messaging':
    - 'Sending Messages': 'basics/messaging.md'
    - 'Message Synchronization': 'basics/message-sync.md'
- 'Authentication':
  - 'Getting Started':
    - 'Node.js': 'missing.md'
    - 'Python': 'missing.md'
    - 'PHP': 'missing.md'
    - 'C#': 'missing.md'
    - 'API Explorer': 'missing.md'
  - 'Developer Manual':
    - 'Auth Types': 'basics/oauth.md'
  - 'Sample Applications':
    - 'Auth Server': 'missing.md'
- 'SMS':
  - 'Getting Started':
    - 'Node.js': 'sms/quick-start/node.md'
    - 'Python': 'sms/quick-start/python.md'
    - 'PHP': 'sms/quick-start/php.md'
    - 'C#': 'sms/quick-start/c-sharp.md'
    - 'API Explorer': 'sms/quick-start/explorer.md'
  - 'Developer Manual':
    - 'Valid Sending Numbers': 'sms/tutorials/valid-sms-numbers.md'
    - 'Sending an SMS': 'sms/tutorials/sending-sms.md'
    - 'Sending Images over SMS': 'sms/tutorials/sending-images.md'
    - 'Saving SMS to a file': 'sms/tutorials/saving-files.md'
    - 'Pager Messages': 'sms/pager.md'
#    - 'Sending to Multiple People (MMS)': 'sms/tutorials/mms.md'
    - 'Tracking Delivery Status': 'sms/tutorials/delivery-status.md'
    - 'Message Histories': 'sms/tutorials/message-histories.md'
    - 'Receiving SMS': 'sms/tutorials/receiving.md'
  - 'API Reference':
    - 'Send SMS': 'https://developer.ringcentral.com/api-reference#SMS-and-MMS-sendSMS'
    - 'Get Message List': 'https://developer.ringcentral.com/api-reference#Fax-listMessages'
    - 'Delete Conversation': 'https://developer.ringcentral.com/api-reference#Fax-deleteMessagesByFilter'
    - 'Get Message(s)': 'https://developer.ringcentral.com/api-reference#Fax-loadMessage'
    - 'Update Message(s)': 'https://developer.ringcentral.com/api-reference#Fax-updateMessage'
    - 'Delete Message(s)': 'https://developer.ringcentral.com/api-reference#Fax-deleteMessage'
    - 'Get Attachment': 'https://developer.ringcentral.com/api-reference#Fax-getMessageAttachmentById'
  - 'Sample Applications':
    - 'SMS Sample App Walkthrough': 'https://ringcentral-tutorials.github.io/sms-api-nodejs-quickstart/'
    - 'A2P SMS Messaging': 'https://ringcentral-tutorials.github.io/a2p-sms-messaging-nodejs-demo/'
    - 'Two-factor Authentication': 'https://ringcentral-tutorials.github.io/sms-2fa-nodejs-demo/'
- 'Voice':
  - 'Getting Started':
    - 'WebRTC':
      - 'Web': 'missing.md'
      - 'iOS': 'missing.md'
      - 'Android': 'missing.md'
    - 'RingOut':
      - 'Node.js': 'voice/quick-start/ringout/node.md'
      - 'Python': 'voice/quick-start/ringout/python.md'
      - 'PHP': 'voice/quick-start/ringout/php.md'
      - 'C#': 'voice/quick-start/ringout/c-sharp.md'
      - 'API Explorer': 'voice/quick-start/ringout/explorer.md'
  - 'Developer Manual': 'missing.md'
  - 'API Reference':
    - 'Make Call': 'https://developer.ringcentral.com/api-reference#RingOut-makeRingOutCall'
    - 'Get Call Status': 'https://developer.ringcentral.com/api-reference#RingOut-getRingOutCallStatus'
    - 'Cancel Call': 'https://developer.ringcentral.com/api-reference#RingOut-cancelRingOutCall'
    - 'Call Status': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-getCallSessionStatus'
    - 'Drop Call': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-deleteCallSession'
    - 'Hold Call': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-holdCallParty'
    - 'Unhold Call': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-unholdCallParty'
    - 'Reject Call': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-rejectParty'
    - 'Transfer Call': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-transferCallParty'
    - 'Forward Call': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-forwardCallParty'
    - 'Flip Call': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-callFlipParty'
    - 'Call Party Status': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-getCallPartyStatus'
    - 'Update Call Party': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-updateCallParty'
    - 'Start Recording': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-startCallRecording'
    - 'Pause/Resume Recording': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-pauseResumeCallRecording'
  - 'Tutorials':
    - 'RingOut': 'voice/ringout.md'
    - 'WebRTC': 'voice/webrtc.md'
    - 'Call Queues': 'voice/call-queues.md'
    - 'Call Control': 'voice/call-control.md'
    - 'Answering Rules': 'voice/answering-rules.md'
    - 'URI Scheme': 'voice/uri-scheme.md'
  - 'Sample Applications':
    - 'Building a Web Phone with WebRTC': 'https://ringcentral-tutorials.github.io/getting-started-with-webrtc-js-demo/'
#    - 'Call Queues': 'missing.md'
#    - 'Salesforce Dialer': 'missing.md'
- 'Fax':
  - 'Getting Started':
    - 'Node.js': 'fax/quick-start/node.md'
    - 'Python': 'fax/quick-start/python.md'
    - 'PHP': 'fax/quick-start/php.md'
    - 'C#': 'fax/quick-start/c-sharp.md'
    - 'API Explorer': 'fax/quick-start/explorer.md'
  - 'Developer Manual':
    - 'Sending Faxes': 'fax/tutorials/sending-faxes.md'
    - 'Receiving Faxes': 'fax/tutorials/receiving-faxes.md'
    - 'Forwarding and Resending': 'fax/tutorials/resending-faxes.md'
  - 'API Reference':
    - 'Create Fax': 'https://developer.ringcentral.com/api-reference#Fax-sendFaxMessage'
    - 'Get Cover Pages': 'https://developer.ringcentral.com/api-reference#Fax-listFaxCoverPages'
    - 'Get Message List': 'https://developer.ringcentral.com/api-reference#Fax-listMessages'
    - 'Delete Conversation': 'https://developer.ringcentral.com/api-reference#Fax-deleteMessagesByFilter'
    - 'Get Message(s)': 'https://developer.ringcentral.com/api-reference#Fax-loadMessage'
    - 'Update Message(s)': 'https://developer.ringcentral.com/api-reference#Fax-updateMessage'
    - 'Delete Message(s)': 'https://developer.ringcentral.com/api-reference#Fax-deleteMessage'
    - 'Get Attachment': 'https://developer.ringcentral.com/api-reference#Fax-getMessageAttachmentById'
  - 'Sample Applications':
    - 'Custom Fax Cover Pages': 'https://ringcentral-tutorials.github.io/fax-cover-page-nodejs-demo/'
- 'Chat':
  - 'Getting Started':
    - 'Node.js': 'chat/quick-start/node.md'
    - 'Python': 'chat/quick-start/python.md'
    - 'PHP': 'chat/quick-start/php.md'
    - 'C#': 'chat/quick-start/c-sharp.md'
    - 'API Explorer': 'chat/quick-start/explorer.md'
  - 'Developer Manual':
    - 'API Overview': 'chat/manual/api.md'
    - 'Message Attachments': 'chat/manual/attachments.md'
  - 'Tutorials':
    - 'Building a Bot Locally': 'chat/tutorials/local-bots.md'
  - 'Sample Applications':
    - 'Glip Bot using IBM Watson and Botkit': 'https://ringcentral-tutorials.github.io/botkit-watson-bot-nodejs-demo/'
    - 'Voicemail Transcription Bot': 'https://ringcentral-tutorials.github.io/ringcentral-ai-bot/'
- 'Call Logs':
  - 'Getting Started':
    - 'Node.js': 'call-log/quick-start/node.md'
    - 'Python': 'call-log/quick-start/python.md'
    - 'PHP': 'call-log/quick-start/php.md'
    - 'C#': 'call-log/quick-start/c-sharp.md'
    - 'API Explorer': 'call-log/quick-start/explorer.md'
  - 'Developer Manual':
    - 'Overview': 'call-log/manual/overview.md'
    - 'Data Archival': 'call-log/manual/archival.md'
    - 'API Basics': 'call-log/manual/api.md'
    - 'Call Recordings': 'call-log/manual/recordings.md'
    - 'Synchronization': 'call-log/manual/sync.md'
    - 'Detailed Call Log Data': 'call-log/manual/details.md'
    - 'Best Practices': 'call-log/manual/best-practices.md'
    - 'Access Control': 'call-log/manual/access.md'
  - 'Sample Applications':
    - 'Call Log Analytics for iOS': 'https://ringcentral-tutorials.github.io/calllog-analytics-swift-demo/'
    - 'Call Log Visualizations': 'https://ringcentral-tutorials.github.io/calllog-visualization-nodejs-demo/'
    - 'Call Recording Push Notification': 'https://ringcentral-tutorials.github.io/callrecording-notification-node/'
