site_name: Developing with RingCentral
site_url: https://github.com/ringcentral/ringcentral-api-docs
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/ringcentral-api-docs
edit_uri: tree/master/docs
docs_dir: docs

plugins:
  - git-committers:
      repository: ringcentral/ringcentral-api-docs
      branch: master
  - bootstrap-tables

theme:
  name: moonstone
  custom_dir: 'theme/'
  fluid_layout: True
  suppress_nextprev: true
  shortcuts:
    - foo

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - codehilite:
      linenums: "None"

extra_css:
- extra.css
- css/mega-menu.css

copyright: "1999-2019 RingCentral, Inc. All rights reserved."

google_analytics: ['UA-57519112-1', 'developers.ringcentral.com']

pages:
- 'The Basics':
  - 'Using the API':
    - 'Methods, Endpoints and Parameters': 'basics/uris.md'
    - 'Exploring the API': 'basics/explorer.md'
    - 'Developing in Sandbox': 'basics/sandbox.md'
    - 'Using Phones in Sandbox': 'basics/your-rc-phone.md'
    - 'Webhooks': 'basics/notifications/webhooks.md'
    - 'Mobile Push Notifications': 'basics/notifications/pubnub.md'
    - 'Rate Limits': 'basics/rate-limits.md'
  - 'Application Management':
    - 'Creating an Application': 'basics/create-app.md'
    - 'Deploying to Production': 'basics/production.md'
    - 'Publishing to App Gallery': 'basics/app-gallery.md'
    - 'Using Lead Forms': 'basics/lead-forms.md'
    - 'Install App Buttons': 'basics/install-app-button.md'
  - 'Account Management':
    - 'Accounts & Extensions': 'basics/configuration/account_extension.md'
    - 'Auth Profile & Permissions': 'basics/configuration/user-permissions.md'
  - 'Messaging':
    - 'Sending Messages': 'basics/messaging.md'
    - 'Message Synchronization': 'basics/message-sync.md'
- 'Authentication':
  - 'Getting Started':
  #  - 'Password Flow':
  #    - 'Node.js': 'authentication/quick-start/password-flow/node.md'
  #    - 'Python': 'authentication/quick-start/password-flow/python.md'
  #    - 'PHP': 'authentication/quick-start/password-flow/php.md'
  #    - 'C#': 'authentication/quick-start/password-flow/c-sharp.md'
    - 'Authorization Flow':
      - 'Node.js': 'authentication/quick-start/authorization-flow/node.md'
      - 'Python': 'authentication/quick-start/authorization-flow/python.md'
      - 'PHP': 'authentication/quick-start/authorization-flow/php.md'
#      - 'C#': 'authentication/quick-start/authorization-flow/c-sharp.md'
  - 'Developer Manual':
    - 'Auth Types': 'basics/oauth.md'

- 'Notifications and Events':
  - 'Getting Started':
    - 'PubNub':
      - 'Node.js': 'notifications/quick-start/pubnub/node.md'
      - 'Python': 'notifications/quick-start/pubnub/python.md'
      - 'PHP': 'notifications/quick-start/pubnub/php.md'
      - 'C#': 'notifications/quick-start/pubnub/c-sharp.md'
    - 'WebHook':
      - 'Node.js': 'notifications/quick-start/webhook/node.md'
      - 'Python': 'notifications/quick-start/webhook/python.md'
      - 'PHP': 'notifications/quick-start/webhook/php.md'
      #- 'C#': 'notifications/quick-start/webhook/c-sharp.md'
#  - 'Developer Manual':

  - 'API Reference':
    - 'Create Subscription': 'https://developer.ringcentral.com/api-reference#Subscriptions-createSubscription'
    - 'Get Subscriptions': 'https://developer.ringcentral.com/api-reference#Subscriptions-listSubscriptions'
    - 'Renew Subscription': 'https://developer.ringcentral.com/api-reference#Subscriptions-updateSubscription'
    - 'Delete Subscription': 'https://developer.ringcentral.com/api-reference#Subscriptions-deleteSubscription'
  - 'Sample Applications':
    - 'Create SMS Push Notification': 'https://ringcentral-tutorials.github.io/sms-api-nodejs-quickstart/'
    - 'A2P SMS Messaging': 'https://ringcentral-tutorials.github.io/a2p-sms-messaging-nodejs-demo/'
#
- 'SMS':
  - 'Getting Started':
    - 'Node.js': 'sms/quick-start/node.md'
    - 'Python': 'sms/quick-start/python.md'
    - 'PHP': 'sms/quick-start/php.md'
    - 'C#': 'sms/quick-start/c-sharp.md'
  - 'Developer Manual':
    - 'Valid Sending Numbers': 'sms/tutorials/valid-sms-numbers.md'
    - 'Sending an SMS': 'sms/tutorials/sending-sms.md'
    - 'Sending Images over SMS': 'sms/tutorials/sending-images.md'
#    - 'Saving SMS to a file': 'sms/tutorials/saving-files.md'
    - 'Pager Messages': 'sms/pager.md'
#    - 'Sending to Multiple People (MMS)': 'sms/tutorials/mms.md'
    - 'Tracking Delivery Status': 'sms/tutorials/delivery-status.md'
    - 'Message Histories': 'sms/tutorials/message-histories.md'
#    - 'Receiving SMS': 'sms/tutorials/receiving.md'
  - 'API Reference':
    - 'Send SMS': 'https://developer.ringcentral.com/api-reference#SMS-and-MMS-sendSMS'
    - 'Delete Conversation': 'https://developer.ringcentral.com/api-reference#SMS-and-MMS-deleteMessagesByFilter'
    - 'Get Message(s)': 'https://developer.ringcentral.com/api-reference#SMS-and-MMS-loadMessage'
    - 'Update Message(s)': 'https://developer.ringcentral.com/api-reference#SMS-and-MMS-updateMessage'
    - 'Delete Message(s)': 'https://developer.ringcentral.com/api-reference#SMS-and-MMS-deleteMessage'
    - 'Get Attachment': 'https://developer.ringcentral.com/api-reference#SMS-and-MMS-getMessageAttachmentById'
  - 'Sample Applications':
    - 'SMS Sample App Walkthrough': 'https://ringcentral-tutorials.github.io/sms-api-nodejs-quickstart/'
    - 'A2P SMS Messaging': 'https://ringcentral-tutorials.github.io/a2p-sms-messaging-nodejs-demo/'
    - 'Two-factor Authentication': 'https://ringcentral-tutorials.github.io/sms-2fa-nodejs-demo/'
- 'Voice':
  - 'Getting Started':
    - 'Node.js': 'voice/quick-start/ringout/node.md'
    - 'Python': 'voice/quick-start/ringout/python.md'
    - 'PHP': 'voice/quick-start/ringout/php.md'
    - 'C#': 'voice/quick-start/ringout/c-sharp.md'
  - 'Developer Manual':
    - 'Place a Call: RingOut': 'voice/ringout.md'
    - 'Place a Call: WebRTC': 'voice/webrtc.md'
    - 'Call Queues': 'voice/call-queues.md'
    - 'Call Control': 'voice/call-control.md'
    - 'Answering Rules': 'voice/answering-rules.md'
    - 'URI Scheme': 'voice/uri-scheme.md'
    - 'Supervising Calls': 'voice/supervision.md'
    - 'Presence': 'voice/presence.md'
  - 'API Reference':
    - 'Make Call': 'https://developer.ringcentral.com/api-reference#RingOut-makeRingOutCall'
    - 'Get Call Status': 'https://developer.ringcentral.com/api-reference#RingOut-getRingOutCallStatus'
    - 'Cancel Call': 'https://developer.ringcentral.com/api-reference#RingOut-cancelRingOutCall'
    - 'Call Status': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-getCallSessionStatus'
    - 'Drop Call': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-deleteCallSession'
    - 'Hold Call': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-holdCallParty'
    - 'Unhold Call': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-unholdCallParty'
    - 'Reject Call': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-rejectParty'
    - 'Transfer Call': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-transferCallParty'
    - 'Forward Call': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-forwardCallParty'
    - 'Flip Call': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-callFlipParty'
    - 'Call Party Status': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-getCallPartyStatus'
    - 'Update Call Party': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-updateCallParty'
    - 'Start Recording': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-startCallRecording'
    - 'Pause/Resume Recording': 'https://developer.ringcentral.com/api-reference#Call-Control-Beta-pauseResumeCallRecording'
  - 'Sample Applications':
    - 'Building a Web Phone with WebRTC': 'https://ringcentral-tutorials.github.io/getting-started-with-webrtc-js-demo/'
- 'Fax':
  - 'Getting Started':
    - 'Node.js': 'fax/quick-start/node.md'
    - 'Python': 'fax/quick-start/python.md'
    - 'PHP': 'fax/quick-start/php.md'
    - 'C#': 'fax/quick-start/c-sharp.md'
  - 'Developer Manual':
    - 'Sending Faxes': 'fax/tutorials/sending-faxes.md'
    - 'Receiving Faxes': 'fax/tutorials/receiving-faxes.md'
    - 'Forwarding and Resending': 'fax/tutorials/resending-faxes.md'
  - 'API Reference':
    - 'Create Fax': 'https://developer.ringcentral.com/api-reference#Fax-sendFaxMessage'
    - 'Get Cover Pages': 'https://developer.ringcentral.com/api-reference#Fax-listFaxCoverPages'
    - 'Get Message List': 'https://developer.ringcentral.com/api-reference#Fax-listMessages'
    - 'Delete Conversation': 'https://developer.ringcentral.com/api-reference#Fax-deleteMessagesByFilter'
    - 'Get Message(s)': 'https://developer.ringcentral.com/api-reference#Fax-loadMessage'
    - 'Update Message(s)': 'https://developer.ringcentral.com/api-reference#Fax-updateMessage'
    - 'Delete Message(s)': 'https://developer.ringcentral.com/api-reference#Fax-deleteMessage'
    - 'Get Attachment': 'https://developer.ringcentral.com/api-reference#Fax-getMessageAttachmentById'
  - 'Sample Applications':
    - 'Custom Fax Cover Pages': 'https://ringcentral-tutorials.github.io/fax-cover-page-nodejs-demo/'
- 'Team Messaging':
  - 'Getting Started':
    - 'Node.js': 'team-messaging/quick-start/node.md'
  - 'Developer Manual':
    - 'Message Attachments': 'team-messaging/manual/attachments.md'
    - 'Building a Bot Locally': 'team-messaging/manual/local-bots.md'
    - 'Bot Frameworks': 'team-messaging/manual/frameworks.md'
  - 'Sample Applications':
    - 'Glip Bot using IBM Watson and Botkit': 'https://ringcentral-tutorials.github.io/botkit-watson-bot-nodejs-demo/'
    - 'Voicemail Transcription Bot': 'https://ringcentral-tutorials.github.io/ringcentral-ai-bot/'
- 'Call Logs':
  - 'Getting Started':
    - 'Node.js': 'call-log/quick-start/node.md'
    - 'Python': 'call-log/quick-start/python.md'
    - 'PHP': 'call-log/quick-start/php.md'
    - 'C#': 'call-log/quick-start/c-sharp.md'
  - 'Developer Manual':
    - 'Overview': 'call-log/manual/overview.md'
    - 'Data Archival': 'call-log/manual/archival.md'
    - 'API Basics': 'call-log/manual/api.md'
    - 'Call Recordings': 'call-log/manual/recordings.md'
    - 'Synchronization': 'call-log/manual/sync.md'
    - 'Detailed Call Log Data': 'call-log/manual/details.md'
    - 'Best Practices': 'call-log/manual/best-practices.md'
    - 'Access Control': 'call-log/manual/access.md'
  - 'Sample Applications':
    - 'Call Log Analytics for iOS': 'https://ringcentral-tutorials.github.io/calllog-analytics-swift-demo/'
    - 'Call Log Visualizations': 'https://ringcentral-tutorials.github.io/calllog-visualization-nodejs-demo/'
    - 'Call Recording Push Notification': 'https://ringcentral-tutorials.github.io/callrecording-notification-node/'

- 'Message Store':
  - 'Getting Started':
    - 'Node.js': 'message-store/quick-start/node.md'
    - 'Python': 'message-store/quick-start/python.md'
    - 'PHP': 'message-store/quick-start/php.md'
    - 'C#': 'message-store/quick-start/c-sharp.md'
  - 'API Reference':
    - 'Get Message List': 'https://developers.ringcentral.com/api-reference#SMS-and-MMS-listMessages'
    - 'Get Message Attachment': 'https://developers.ringcentral.com/api-reference#SMS-and-MMS-getMessageAttachmentById'
    - 'Delete Message(s)': 'https://developers.ringcentral.com/api-reference#SMS-and-MMS-deleteMessage'
    - 'Sync Messages': 'https://developers.ringcentral.com/api-reference#SMS-and-MMS-syncMessages'

    # - 'SMS':
    #   - 'Node.js': 'message-store/quick-start/sms/node.md'
    #   - 'Python': 'message-store/quick-start/sms/python.md'
    #   - 'PHP': 'message-store/quick-start/sms/php.md'
    #   - 'C#': 'message-store/quick-start/sms/c-sharp.md'
#     - 'Fax':
#       - 'Node.js': 'message-store/quick-start/fax/node.md'
#       - 'Python': 'message-store/quick-start/fax/python.md'
#       - 'PHP': 'message-store/quick-start/fax/php.md'
#       - 'C#': 'message-store/quick-start/fax/c-sharp.md'
#     - 'MMS':
#       - 'Node.js': 'message-store/quick-start/mms/node.md'
#       - 'Python': 'message-store/quick-start/mms/python.md'
#       - 'PHP': 'message-store/quick-start/mms/php.md'
#       - 'C#': 'message-store/quick-start/mms/c-sharp.md'
  #  - 'Developer Manual':

- 'Meetings':
  - 'Getting Started':
    - 'Node.js': 'meetings/quick-start/node.md'
    - 'Python': 'meetings/quick-start/python.md'
    - 'PHP': 'meetings/quick-start/php.md'
    - 'C#': 'meetings/quick-start/c-sharp.md'
#  - 'Developer Manual':
#    - 'Scheduling a Meeting': 'meetings/manual/schedule.md'
#    - 'Meeting Recordings': 'meetings/manual/recordings.md'
  - 'API Reference':
    - 'Get Scheduled Meetings': https://developer.ringcentral.com/api-reference#Upcoming-Meetings-listMeetings
    - 'Create Meetings': https://developer.ringcentral.com/api-reference#Upcoming-Meetings-createMeeting
    - 'Get Meeting Info': https://developer.ringcentral.com/api-reference#Upcoming-Meetings-loadMeeting
    - 'Update Meeting': https://developer.ringcentral.com/api-reference#Upcoming-Meetings-updateMeeting
    - 'Delete Meeting': https://developer.ringcentral.com/api-reference#Upcoming-Meetings-deleteMeeting
    - 'End Meeting': https://developer.ringcentral.com/api-reference#Active-Meetings-endMeeting
    - 'Get Meeting Service Info': https://developer.ringcentral.com/api-reference#Meetings-Configuration-loadMeetingServiceInfo
    - 'Get Account Meeting Recordings': https://developer.ringcentral.com/api-reference#Meeting-Recordings-listAccountMeetingRecordings
    - 'Get User Meeting Recordings': https://developer.ringcentral.com/api-reference#Meeting-Recordings-listUserMeetingRecordings
