site_name: Developing with RingCentral
site_url: https://github.com/ringcentral/ringcentral-api-docs
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/ringcentral-api-docs
edit_uri: 
docs_dir: docs
theme:
  name: null
  custom_dir: bootstrap4-theme
  suppress_nextprev: true
  highlightjs: true
  hljs_languages:
    - http
  hljs_style: github
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
extra_css: [extra.css]
extra_javascript: [fonts.js]
copyright: 2018, RingCentral, Inc.
google_analytics: ['UA-57519112-5', 'ringcentral-api-docs.readthedocs.io']
pages:
- 'Home': 'index.md'
- 'Quick Start': 'quick-start/index.md'
- 'Development Basics': 
  - 'Authentication': 'basics/oauth.md'
  - 'URIs': 'basics/uris.md'
  - 'Rate Limits': 'basics/rate-limits.md'
  - 'Notifications':
    - 'Overview': 'notifications/index.md'
    - 'Webhooks': 'notifications/webhooks.md'
    - 'PubSub': 'notifications/pubsub.md'
  - 'Messaging':
    - 'Sending Messages': 'basics/messaging.md'
    - 'Message Synchronization': 'basics/message-sync.md'
  - 'Publishing Your App': 'basics/publish.md'
  - 'Upgrading from Legacy API': 'basics/legacy_api_upgrade.md'
- 'Products':
  - 'Configuration':
    - 'Account & Extension Settings': 'configuration/account_extension.md'
    - 'Auth Profile & Permissions': 'configuration/authorization_profile.md'
  - 'Data': 
    - 'Call Logs': 'data/call-logs/index.md'
    - 'Data Archival': 'data/archival.md'
  - 'Fax': 'fax/index.md'
  - 'Glip Messaging':
    - 'API': 'glip/api.md'
    - 'Message Attachments': 'glip/attachments.md'
    - 'Bots': 'glip/bots.md'
  - 'SMS/MMS': 'sms/index.md'
  - 'Voice':
    - 'RingOut': 'voice/ringout.md'
    - 'WebRTC': 'voice/webrtc.md'
    - 'Call Queues': 'voice/call-queues.md'
    - 'Call Control': 'voice/call-control.md'
    - 'Answering Rules': 'voice/answering-rules.md'
    - 'URI Scheme': 'voice/uri-scheme.md'

#- 'Messaging':
#    - 'Message Synchronization': 'messages_sync.md'
